Diary/Models/Diary.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Diary.Models
{
    public class DiaryModel
    {
        public int Id { get; set; }
        [Required]
        [MinLength(5)]
        [RegularExpression(@"^.*\S.*$", ErrorMessage ="Title cannot contains only white spaces!")]
        [StringLength(200)]
        public string Title { get; set; }
        [Required]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "Entry cannot contains only white spaces!")]
        public string Entry { get; set; }
        [Required]
        [Range(1,365)]
        public int Day { get; set; }

    }
}

Diary/Models/ErrorViewModel.cs
using System;

namespace Diary.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Diary/Controllers/DiaryController.cs
using Diary.Context;
using Diary.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diary.Controllers
{
    public class DiaryController : Controller
    {
        private readonly DiaryContext _context;
        public DiaryController(DiaryContext context)
        {
            _context = context;
        }

        public async Task<ActionResult<IEnumerable<DiaryModel>>> Index()
        {
            return View(await _context.DiaryEntry.ToListAsync());
        }


        [HttpGet("/Diary/Show/{id}")]
        public async Task<ActionResult<DiaryModel>>Show(int id)
        {
            var entry = await _context.DiaryEntry.FindAsync(id);

            if (entry == null)
            {
                return NotFound();
            }

            return View(entry);
        }

        [HttpGet("Diary/Delete/{id}")]
        public async Task<ActionResult<DiaryModel>> Delete(int id)
        {
            var entry = await _context.DiaryEntry.FindAsync(id);
           if (entry == null)
            {
                return NotFound();
            }

            _context.DiaryEntry.Remove(entry);
            await _context.SaveChangesAsync();
         
            return View(entry);
        }

        [HttpGet("/Diary/Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<DiaryModel>> Save(DiaryModel diaryModel)
        {
            _context.DiaryEntry.Add(diaryModel);
            await _context.SaveChangesAsync();

            return View(diaryModel);
        }






    }
}

Diary/Views/Diary/Create.cshtml
@model Diary.Models.DiaryModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create new diary entry</h1>

<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Save">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" required />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Entry" class="control-label"></label>
                <textarea asp-for="Entry" class="form-control" rowsrequired rows="10"></textarea>
                <span asp-validation-for="Entry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" required/>
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-secondary" asp-action="Index">Back to dairy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Diary/Views/Diary/Delete.cshtml
@model Diary.Models.DiaryModel

@{
    ViewData["Title"] = "Delete";
}

<div class="alert alert-danger" role="alert">
    You deleted entry <span class="font-weight-bold">@Html.DisplayFor(model => model.Title)</span> 
</div>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-secondary" asp-action="Index">Back to diary</a>
</div>

Diary/Views/Diary/Index.cshtml
@model IEnumerable<Diary.Models.DiaryModel>

@{
    ViewData["Title"] = "Diary entries";
}

<h1>Diary entries</h1>

<p>
    <a class="btn btn-outline-primary" asp-action="Create" method="post">Create new diary entry</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Show" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Day)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Diary/Views/Diary/Save.cshtml
@model Diary.Models.DiaryModel

@{
    ViewData["Title"] = "Save";
}

<div class="alert alert-primary" role="alert">
    You created entry <span class="font-weight-bold">@Html.DisplayFor(model => model.Title)</span>
</div>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-secondary" asp-action="Index">Back to diary</a>
</div>

Diary/Views/Diary/Show.cshtml
@model Diary.Models.DiaryModel

@{
    ViewData["Title"] = "Diary entry";
}

<h1>@Html.DisplayFor(model => model.Title)</h1>

    <hr />
    <div class="row">
        <div class="col-12">
            <p class="text-muted"><span class="font-weight-bold">@Html.DisplayNameFor(model => model.Day)</span> @Html.DisplayFor(model => model.Day)</p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <p>@Html.DisplayFor(model=>model.Entry)</p>
        </div>
    </div>
<div>
    <a class="btn btn-outline-secondary" asp-action="Index">Back to diary</a>
</div>

Diary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Diary" asp-action="Index">Diary</a>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            summ-it - Diary
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>